# https://github.com/quipper/comment-failure-action
on:
  workflow_run:
    workflows:
      - pytest
      - snyk
    types: [ completed ]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1